# Generated by Django 6.1.2 on 2026-10-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='release_date',
            new_name='date',
        ),
    ]
